### ISSUE TITLE
Copyright Violation

### ISSUE THREAD

**Issue by Lilithbunny** [Chaython/7-Zip-ZSTD-Portable#1]
Due to the recent updates of Pure, You have a repository that contains content that violates our copyright, please remove any repository that is related to Pure, failure to do so within 6-7 business days will result in the termination of said repository.

**Comment by Chaython** [comment]
I don't know what you are talking about.

**Comment by Chaython** [comment]
> Due to the recent updates of Pure, You have a repository that contains content that violates our copyright, please remove any repository that is related to Pure, failure to do so within 6-7 business days will result in the termination of said repository.

I see you are referring to an unrelated fork. I don't know who you spoke to, but you can't change the terms of the license without notice, as there's no disclaimer within the original license allowing for future changes to the terms.
Even as of the last commit, the license even after your modification still allowed distribution.
You could host a future revision which has a different license. But it doesn't affect versions that predate the license.
Your license permitted modifying as well. So I could continue to merge your future commits, by writing it myself.
